# Generated by Django 4.2.4 on 2023-10-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0046_alter_product_reviewer'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
