# Generated by Django 4.2.4 on 2023-10-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
