# Generated by Django 4.2.5 on 2023-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10, null=True, verbose_name='Цена'),
        ),
    ]
