# Generated by Django 4.2.4 on 2023-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(max_length=10, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.CharField(max_length=10, null=True, verbose_name='Толщина'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=10, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(max_length=10, null=True, verbose_name='Ширина'),
        ),
    ]
