# Generated by Django 4.2.4 on 2023-09-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_remove_product_thickness_alter_product_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
