# Generated by Django 4.2.4 on 2023-09-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_product_discount_price_product_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
