# Generated by Django 4.2.4 on 2023-09-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_product_end_time_alter_product_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
