# Generated by Django 4.2.4 on 2023-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, null=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.CharField(max_length=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания распродажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=5, null=True, verbose_name='Цена (руб)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата старта распродажи'),
        ),
    ]
