# Generated by Django 4.2.4 on 2023-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.CharField(choices=[('в наличии', 'В наличии'), ('не в наличии', 'Не в наличии')], default='в наличии', max_length=12, null=True, verbose_name='В наличии'),
        ),
    ]
