# Generated by Django 4.2.4 on 2023-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_remove_product_available_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.CharField(choices=[('в наличии', 'В наличии'), ('не в наличии', 'Не в наличии')], default='в наличии', max_length=12, null=True, verbose_name='Наличие'),
        ),
    ]
