# Generated by Django 4.2.4 on 2023-10-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_alter_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.AddField(
            model_name='product',
            name='available_status',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
