# Generated by Django 4.2.4 on 2023-10-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_remove_product_is_available_product_available_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12, null=True, verbose_name='Наличие')),
                ('is_available', models.BooleanField(null=True, verbose_name='Наличие')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='available_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.available'),
        ),
    ]
