# Generated by Django 4.2.4 on 2023-10-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_available_alter_product_available_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
    ]
