# Generated by Django 4.2.4 on 2023-10-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0024_alter_product_available_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_status',
            field=models.BooleanField(choices=[('в наличии', 'В наличии'), ('не в наличии', 'Не в наличии')], null=True, verbose_name='Наличие'),
        ),
    ]
