# Generated by Django 4.2.4 on 2023-10-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_alter_product_available_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_status', models.BooleanField(verbose_name='Наличие')),
            ],
        ),
    ]
