# Generated by Django 4.2.4 on 2023-10-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0026_productavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailability',
            name='availability_status',
            field=models.BooleanField(choices=[('в наличии', 'В наличии'), ('не в наличии', 'Не в наличии')], verbose_name='Наличие'),
        ),
    ]
