# Generated by Django 4.2.4 on 2023-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0029_alter_productavailability_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailability',
            name='availability_status',
            field=models.BooleanField(verbose_name='Наличие'),
        ),
    ]
