# Generated by Django 4.2.4 on 2023-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0032_remove_productavailability_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productavailability',
            name='status_choices',
            field=models.CharField(max_length=12, null=True, verbose_name='Статус товара'),
        ),
    ]
