# Generated by Django 4.2.4 on 2023-10-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0033_productavailability_status_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productavailability',
            old_name='status_choices',
            new_name='availability_status',
        ),
    ]
