# Generated by Django 4.2.4 on 2023-10-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0037_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(max_length=10, null=True, verbose_name='Ширина (см)'),
        ),
    ]
