# Generated by Django 4.2.4 on 2023-10-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0038_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
