# Generated by Django 4.2.4 on 2023-10-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main_page', '0043_rename_owner_review_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
