# Generated by Django 4.2.4 on 2023-10-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_username'),
        ('main_page', '0047_alter_product_reviewer_alter_review_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'product')},
        ),
    ]
