# Generated by Django 4.2.4 on 2023-10-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0049_alter_review_body_alter_review_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200, verbose_name="Голос 'положительный/отрицательный'"),
        ),
    ]
