# Generated by Django 4.2.4 on 2023-10-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0050_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('За', 'За'), ('Против', 'Против')], max_length=200, verbose_name='Голос'),
        ),
    ]
