# Generated by Django 4.2.4 on 2023-10-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_alter_shoppingcart_options_and_more'),
        ('main_page', '0051_alter_review_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shoppingcart'),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('За', 'За'), ('Против', 'Против')], max_length=200, null=True, verbose_name='Голос'),
        ),
    ]
