# Generated by Django 4.2.4 on 2023-10-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0052_product_card_alter_review_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='card',
        ),
    ]
