# Generated by Django 4.2.4 on 2023-10-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0052_product_card_alter_review_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='card',
            new_name='card_prod',
        ),
    ]
