# Generated by Django 4.2.4 on 2023-10-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0009_alter_shoppingcart_img_alter_shoppingcart_price_and_more'),
        ('main_page', '0053_remove_product_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_prods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shoppingcart'),
        ),
    ]
