# Generated by Django 4.2.4 on 2023-11-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0054_product_cart_prods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('за', 'Голос за'), ('против', 'Голос против')], max_length=200, null=True, verbose_name='Голос'),
        ),
    ]
