# Generated by Django 4.2.7 on 2023-11-15 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0059_favouritestatus_comparestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorites_statuses',
            field=models.ManyToManyField(blank=True, through='main_page.FavouriteStatus', to=settings.AUTH_USER_MODEL),
        ),
    ]
