# Generated by Django 4.2.7 on 2023-11-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0061_rename_favorites_statuses_product_favorite_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritestatus',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favouritestatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='favorite_status',
        ),
        migrations.DeleteModel(
            name='CompareStatus',
        ),
        migrations.DeleteModel(
            name='FavouriteStatus',
        ),
    ]
