# Generated by Django 4.2.7 on 2023-11-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0062_remove_favouritestatus_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviewer',
        ),
    ]
