# Generated by Django 4.2.5 on 2023-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Наименование')),
                ('img', models.ImageField(null=True, upload_to='main_page/images', verbose_name='Изображение')),
                ('price', models.CharField(max_length=10, null=True, verbose_name='Цена')),
            ],
        ),
    ]
