# Generated by Django 4.2.5 on 2023-09-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_favourite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='description',
            field=models.TextField(max_length=350, null=True, verbose_name='Описание'),
        ),
    ]
