# Generated by Django 4.2.4 on 2023-09-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0004_alter_favourite_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ('product',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
