# Generated by Django 4.2.4 on 2023-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0007_alter_favourite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
