# Generated by Django 4.2.4 on 2023-09-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0008_favourite_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='height',
            field=models.CharField(max_length=10, null=True, verbose_name='Высота (см)'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='weight',
            field=models.CharField(max_length=10, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='width',
            field=models.CharField(max_length=10, null=True, verbose_name='Ширина (см)'),
        ),
    ]
