# Generated by Django 4.2.5 on 2023-09-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0012_favourite_description_favourite_height_favourite_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='product',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Наименование'),
        ),
    ]
