# Generated by Django 4.2.4 on 2023-10-04 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_alter_product_is_available'),
        ('favourites', '0015_alter_favourite_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.product', verbose_name='Описание'),
        ),
    ]
