# Generated by Django 4.2.4 on 2023-10-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0009_alter_shoppingcart_img_alter_shoppingcart_price_and_more'),
        ('favourites', '0016_alter_favourite_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='cart_prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shoppingcart'),
        ),
    ]
