# Generated by Django 4.2.4 on 2023-09-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': (('product',),), 'verbose_name': 'Корзина товаров'},
        ),
    ]
