# Generated by Django 4.2.4 on 2023-09-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_alter_shoppingcart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('product',), 'verbose_name': 'Корзины', 'verbose_name_plural': 'Корзина'},
        ),
    ]
