# Generated by Django 4.2.4 on 2023-10-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_alter_shoppingcart_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('name',), 'verbose_name': 'Корзины', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='product',
            new_name='name',
        ),
    ]
