# Generated by Django 4.2.4 on 2023-09-13 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Наименование')),
                ('img', models.ImageField(null=True, upload_to='main_page/images', verbose_name='Изображение')),
                ('price', models.CharField(max_length=10, null=True, verbose_name='Цена')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
