# Generated by Django 4.2.4 on 2023-09-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_comparison', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compare',
            options={'ordering': ('product',), 'verbose_name': 'Сравнения товаров'},
        ),
    ]
