# Generated by Django 4.2.4 on 2023-09-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_comparison', '0002_alter_compare_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compare',
            options={'ordering': ('product',), 'verbose_name': 'Сравнение товара', 'verbose_name_plural': 'Сравнение товаров'},
        ),
    ]
