# Generated by Django 4.2.4 on 2023-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_comparison', '0004_compare_height_compare_thickness_compare_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='thickness',
        ),
        migrations.AlterField(
            model_name='compare',
            name='height',
            field=models.CharField(max_length=10, null=True, verbose_name='Высота (см)'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='price',
            field=models.CharField(max_length=10, null=True, verbose_name='Цена (руб)'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='weight',
            field=models.CharField(max_length=10, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='width',
            field=models.CharField(max_length=10, null=True, verbose_name='Ширина (см)'),
        ),
    ]
