# Generated by Django 4.2.4 on 2023-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_comparison', '0005_remove_compare_thickness_alter_compare_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
