# Generated by Django 4.2.4 on 2023-10-04 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_alter_product_is_available'),
        ('prod_comparison', '0009_compare_height_compare_img_compare_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='height',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='img',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='price',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='width',
        ),
        migrations.AlterField(
            model_name='compare',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.product', verbose_name='Наименование'),
        ),
    ]
