# Generated by Django 4.2.4 on 2023-10-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0009_alter_shoppingcart_img_alter_shoppingcart_price_and_more'),
        ('prod_comparison', '0010_remove_compare_height_remove_compare_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='cart_prods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shoppingcart'),
        ),
    ]
