# Generated by Django 4.2.4 on 2023-10-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_comparison', '0012_alter_compare_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compare',
            options={'ordering': ('product',), 'verbose_name': 'Сравнение товара', 'verbose_name_plural': 'Сравнение товаров'},
        ),
        migrations.RenameField(
            model_name='compare',
            old_name='products',
            new_name='product',
        ),
    ]
