# Generated by Django 4.2.4 on 2023-10-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_comparison', '0013_alter_compare_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='cart_products',
        ),
    ]
