# Generated by Django 4.2.4 on 2023-10-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0054_product_cart_prods'),
        ('prod_comparison', '0014_remove_compare_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.product', verbose_name='Продукт'),
        ),
    ]
